# Our project Bible

service: inventmgmt

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: graphql.graphqlHandler
    events: 
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: graphql
          method: post
          cors: true

resources:
  Resources:
    questionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: itemsTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
          - AttributeName: price
            AttributeType: N
          - AttributeName: quantity
            AttributeType: N
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


plugins: 
  - serverless-offline